# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField()),
                ('credit_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CreditGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('is_admin', models.BooleanField(default=False)),
                ('credit_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CreditGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='creditscore',
            name='from_credit_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_credit_user', to='app.CreditUser'),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='to_credit_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_credit_user', to='app.CreditUser'),
        ),
    ]
