# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('privateurl', '0001_initial'),
        ('app', '0003_creditgroup_privateurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='credituser',
            name='privateurl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='privateurl.PrivateUrl'),
        ),
    ]
