# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_credituser_privateurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditgroup',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='credituser',
            name='credit_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_users', to='app.CreditGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='credituser',
            unique_together=set([('credit_group', 'email')]),
        ),
    ]
