# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170830_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='credituser',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
