# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_credituser_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='credituser',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
